### PR TITLE
Quote JSON Strings

### PR DESCRIPTION
**Pull request by chancancode**
The previous approach causes problems when there are e.g. newlines in the pull request body. Also, the `draft` parameter was previously passed as a JSON string (`"draft": "true"` and `"draft": "false"`, as opposed to `"draft": true` and `"draft": false`), which I suspect is just a bug.

### CODE REVIEW

**Comment by chancancode** [comment]
While working on this, I discovered two other issues:

1. When the last `curl` fails for any reason (e.g. invalid JSON in my case), it does not report a failure (exit with non-zero)

2. The "check for existing pull request" should not try to match against the pull request body. However, I actually don't think the step to check for duplicates is necessary at all, as GitHub simply won't allow you to have two different pull requests with identical "head" and "base" – after all, pull requests merges the contents of a branch into another branch, not just specific commits, so two pull requests with identical "head" and "base" are by definition identical in every way.

  If you try to do this (as the script would, since the check was wrong), you will get this error from GitHub:

  ```json
  {
    "message": "Validation Failed",
    "errors": [
      {
        "resource": "PullRequest",
        "code": "custom",
        "message": "A pull request already exists for ember-learn:super-rentals-tutorial."
      }
    ],
    "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"
  }
  ```

  So, I think all you would have to do is to send the second request, and check the response for the "A pull request already exists" error (you can probably just `grep` the whole response for that substring). If it is a successful response, or the error matches that string, exit cleanly, otherwise, print the error and exit with a non-zero error code.

**Comment by vsoch** [comment]
hey @chancancode ! The contributor that added the true/false chose to represent them as a string, which (as long as the instructions are clear) wouldn't be an issue. You are saying that your preference is for true / false, do you think this is the better / more intuitive implementation? Could you explain to me how this is different (setting to "true" or "false":

```bash
    if [[ "${5}" ==  "true" ]]; then                         # if PRs are draft
      DRAFT="true";
    else
      DRAFT="false";
    fi
```
than what you are describing? And could you show me an action (or screenshot) of the changes working (your tests?)

**Comment by vsoch** [comment]
Your second suggestion would work - do you want to add to this PR and demonstrate the test? Thank you!

**Comment by chancancode** [comment]
@vsoch it is being _sent over the wire_ as a string, in the JSON (as far as I can tell). i.e., before this commit the `curl` command was sending this to GitHub:

```json
{
  "title": "...some title...".
  ...
  "draft": "true"
}
```

This is because L64 in the old diff:

```bash
DATA="{\"title\":\"${TITLE}\", ..., \"draft\":\"${DRAFT}\"}"
```

The GitHub documentation requires the `draft` key to be a JSON Boolean value. I'm not sure why it wasn't causing problems (maybe it is? don't know, as I was debugging other problems I had at the time). In any case, it seems good to send the value properly so I changed it.

**Comment by vsoch** [comment]
Oh understood, thanks for the clarification! I wonder how it worked for the previous author (that added the feature?) In any ways, this change is definitely good. I'm happy to merge here - do you want to discuss the other bugs in this PR or open another?

**Comment by chancancode** [comment]
@vsoch The "exit code/duplicate PR" problem isn't directly related to what I was fixing here (multiple strings in the body). I'd prefer to do it separately – I also probably won't have time myself since I'm going on vacation today. Maybe we can convert it into an issue and perhaps someone else can pick it up!

As for this code in the PR, I tested it here: https://github.com/ember-learn/test-gh-actions/commit/9e6af732e0e1386cd95579e184b9f862a0e9ca41/checks

**Comment by chancancode** [comment]
@vsoch me too! my best guess is GitHub must be using a certain weakly typed language that is happy to cast `"true", "false"` into `true, false`.. or that it was setting everyone's pull requests to draft..?

```
¯\_(ツ)_/¯
```

**Comment by vsoch** [comment]
Thanks @chancancode - the test looks good, and I'm grateful for your fix here! The GitHub API is one of my favorites, but I'm sure it has a bug every now and then. I'll open up the issue to address the curl return code. Merging - enjoy your vacation! :tropical_drink:

**Pull request merged**
