### PR TITLE
adding title and body

### PR DESCRIPTION
**Pull request by vsoch**
This will address #1 by exposing the body and title specification for the post.

### CODE REVIEW

**Comment by JonasJurczok** [comment]
Awesome, thank you :)

**Comment by vsoch** [comment]
okay, merging! Give it a try, and let me know if it works for you.

**Comment by JonasJurczok** [comment]
I will as soon as I found out how to push to a repo from a github action :)

**Comment by vsoch** [comment]
Hmm, I'm not sure I would be okay doing that (why I did a PR, so it can be reviewed first), but I don't understand your use case entirely! Either way, here is a good place for inspiration and learning :point_right:  https://github.com/sdras/awesome-actions

**Comment by JonasJurczok** [comment]
Yeah I've seen that list :)

My use case is that I want to generate a release branch from my commits, following the semantic release approach. According to the docs (and a couple actions) it should be possible but it isn't. Seems to be a bug, though...

**Comment by vsoch** [comment]
You can just create an action that fires on pushes to master, and then makes a commit to your release branch. If you are having a hard time with actions, this is fairly straight forward to trigger with standard CI like CircleCI.

**Comment by JonasJurczok** [comment]
Yeah getting it to start is not the issue. Getting it to push to the remote branch without freaking out about the workflow file is the issue :)

https://github.com/JonasJurczok/semantic-release-kotlin/runs/81626425

**Comment by vsoch** [comment]
Read the error message closely:

```
 ! [remote rejected] prepare-release -> prepare-release (refusing to allow an integration to create .github/main.workflow)
```
You aren't allowed to create a new github action (the main.workflow file) so just try removing that from the branch you are going to push first.

**Comment by JonasJurczok** [comment]
Yeah but.. I have no changes there.
And if I remove the file I cannot really merge the branch back without removing the workflows itself :)

**Comment by vsoch** [comment]
That's the rule, and it's a good one at that - imagine if someone could pro grammatically spawn off new workflows? That's a huge security risk.

If your branch is a release, you don't need to have the GitHub actions file there. You shouldn't need to merge the release branch back to master either, if you are doing this possibly rethink your workflow. The release branch doesn't need to run actions. If this is a deal breaker for you, then you need to use a different CI.

**Comment by JonasJurczok** [comment]
I totally understand that this is a security risk.
My point is that I'm not modifying the file. It is exactly the same as in the master branch.

And I need to merge it back because I change version information in my pom.xml (java maven project). Not having that in the checked out code makes development so much harder.

**Comment by vsoch** [comment]
If you don't agree with the functionality, you should take it up with GitHub. Good luck!

**Comment by vsoch** [comment]
Note that you aren't just pushing a file already there, you are creating a new branch. One workaround could be to create the branch (a fork of the main one) first, and then the file truly won't be updated and maybe the push would work.

**Pull request merged**
