### PR TITLE
Add/support null branch

### LINKED ISSUE #20: Action is a noop (and no errors) when trigger is `release: [published]`
Currently if the trigger is a `release: [published]`, the [`BRANCH` variable](https://github.com/vsoch/pull-request-action/blob/e54bcbb815225f58f7c672a1a2eb065771532fc6/pull-request.sh#L109-L112) results in value of `null` and as such makes the action act as a `noop`. This also creates no errors in the run.

Screen Shot 2020-03-17 at 10 32 53

To reproduce you can take a look at [this](https://github.com/conjurinc/playroom/blob/df256bb8bda32ff88c87a6bfc78ba452d42d1c8c/.github/workflows/update-suite-release-pr.yml) sample action file

### PR DESCRIPTION
**Pull request by vsoch**
This will add support for `PULL_REQUEST_FROM_BRANCH`, which is honored either in place of deriving the branch from the payload, or absolutely required. This includes commits from #21 and should close #20 .

### CODE REVIEW

**Comment by sgnn7** [comment]
@vsoch Just a minor note but I've been seeing some error checking failures in the code even though you have `set -e` but that's probably for another issue.

**Comment by vsoch** [comment]
@sgnn7 can you show me where you've tested this? You can test directly from this branch:

```
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@add/support-null-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
```
I won't do any kind of merge and release until you've been able to plug this into a workflow and verify it resolves the issue you were having.

**Comment by vsoch** [comment]
And yes please also report any issues that you see so they might be addressed.

**Comment by sgnn7** [comment]
@vsoch let me test that and I'll ping you back here on the results

**Comment by sgnn7** [comment]
@vsoch It's working! :)

- **Action Code:** [update-suite-release-pr.yml](https://github.com/conjurinc/playroom/blob/31ececa38a07b4903e4781d22eee87e81e0b6cdb/.github/workflows/update-suite-release-pr.yml)
- **Trigger:** https://github.com/conjurinc/playroom/releases/tag/v1.2.3
- **Action run:** https://github.com/conjurinc/playroom/runs/514409344?check_suite_focus=true
- **PR created:** https://github.com/conjurinc/playroom/pull/90

PS: Some of these links might disappear as I continue to work on this.

**Comment by vsoch** [comment]
Haha, I think the repository is private so I can't actually see any of them :) Let me quickly test on my testing branch to make sure the old way works, and if that works (and you still give the A-OK) we can release. Back in a bit!

**Comment by sgnn7** [comment]
ah darn it - forgot that the playroom repo is locked up but it does work for the `release:[published]` case for sure. I'll tack on some screenshots.

**Comment by vsoch** [comment]
okay sounds good :) I'm testing on my repository now, should know shortly as well.

**Comment by sgnn7** [comment]
Code:
```
on:
  release:
    types:
      - published
...
jobs:
  persist-new-suite-yml:
    name: Commit Suite Release YML
    runs-on: ubuntu-latest

    steps:
...
    - name: Set BRANCH_NAME
      run: |
        tag_name=${{github.event.release.tag_name}}
        echo "Tag: $tag_name"

        version=$(echo "$tag_name" | sed 's/^v//')
        echo "Version: $version"

        echo "::set-output name=suite_version::${version}"
        echo "::set-output name=suite_update_branch::suite_${version}"
      id: data

    - name: Permanently save the new suite release
      run: |
        mkdir -p releases

        new_suite_version_yml="releases/suite_${{ steps.data.outputs.suite_version }}.yml"
        echo "Suite target file: $new_suite_version_yml"

        cp suite.yml "${new_suite_version_yml}"

        git add "${new_suite_version_yml}"
        git commit -m "Suite v${{ steps.data.outputs.suite_version }} auto-commit of new release files"

    - name: Push files
      run: |
        git push --force "https://${{ github.actor }}:${{secrets.GITHUB_TOKEN}}@github.com/${{ github.repository }}.git" "HEAD:${{ steps.data.outputs.suite_update_branch }}"

    - name: Open a PR to the default branch
      uses: vsoch/pull-request-action@add/support-null-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_FROM_BRANCH: "${{ steps.data.outputs.suite_update_branch }}"
        PULL_REQUEST_BRANCH: master
        PULL_REQUEST_TITLE: "Action: Update suite release file for v${{ steps.data.outputs.suite_version }}"
        PULL_REQUEST_BODY: "Auto-generated PR!"
```

-----

Screen Shot 2020-03-17 at 12 27 00

-----

Screen Shot 2020-03-17 at 12 26 31

**Comment by vsoch** [comment]
This is beautiful - mine worked as well! If it's alright with you, can I add your recipe to an examples folder? I think it's a likely and useful use case, and better than the dummy example that I provided.

**Comment by sgnn7** [comment]
Absolutely :) 👍

**Comment by sgnn7** [comment]
(the branch name of the action might need to be updated though)

**Comment by vsoch** [comment]
Yep just did that, I'm updating to 1.0.2 so that it will coincide with the release of it. Coming soon!

**Pull request merged**
